### PR TITLE
add check for negative ignore patterns

### LINKED ISSUE #409: Does not match for negative ignore
I have following structure:
```
data
├── section
│   └── file1.json
└── section_2
    └── file2.json
```

When I run
```
glob.sync('**', { ignore: ['!data/section/**'] }
```
I expect to get `[ 'data/section/file1.json' ]` but got an empty array.

In a real-world scenario (for similar files structure) I receive a set of project-root globs, but I need to get files from specific section only (without modifying globs). That's why I need for negative pattern in ignore

### PR DESCRIPTION
**Pull request by zaverden**
Close #409

### CODE REVIEW

**Comment by maddygoround** [comment]
is this going to be merged anytime soon?

**Comment by zaverden** [comment]
I have updated the PR to the latest main. All tests pass

**Comment by Lms24** [comment]
Hi @isaacs we (Sentry.io) would love to see this PR get merged. We're currently trying to find a way to handle negated ignores with your library for one of our [new projects](https://github.com/getsentry/sentry-javascript-bundler-plugins) and we came across this PR. Is there anything we can do to help you to merge this? Happy to spend some time!

I've seen that this PR adds one test but maybe we should add a few more to make sure, negated ignores work properly?

**Comment by isaacs** [comment]
No longer relevant in v9.

**Pull request closed without merging**
