### PR TITLE
Use container-based infrastructure for faster build

### PR DESCRIPTION
**Pull request by shinnn**
* ~~Test on io.js and Node 0.12~~ (Landed in https://github.com/isaacs/node-glob/commit/7da66aa90bfd74ee1a839aae0dba96ef4ec0cab8)
* Use [container-based infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) for faster build

### CODE REVIEW

**Comment by shinnn** [comment]
Oh, "Test on io.js and Node 0.12" is included in https://github.com/isaacs/node-glob/pull/188 and that was merged :clap: . I'll remove it from this PR to resolve merge conflicts.

**Comment by shinnn** [comment]
Updated.

**Comment by shinnn** [comment]
Related official blog post: http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

**Comment by shinnn** [comment]
Currently Travis CI shows this message on non-container based builds.

https://travis-ci.org/isaacs/node-glob/jobs/71010066

image

> legacy infrastructure

It seems that the service strongly recommends using container-based infrastructure.

**Comment by shinnn** [comment]
What is blocking this being merged?

**Comment by isaacs** [comment]
updated travis to match my other projects.

**Pull request closed without merging**
