### PR TITLE
[Refactor] use more explicit `assert.ok`

### PR DESCRIPTION
**Pull request by ljharb**
This is a tiny refactor, hopefully it's acceptable.

(We'll all be much happier if you choose not to ask why i need this change :-) )

### CODE REVIEW

**Comment by nicolas377** [comment]
@isaacs does this need documentation since it's such a small change?

**Comment by ljharb** [comment]
I'd assume not; virtually nobody but me's going to notice.

**Comment by ljharb** [comment]
@nicolas377 see the second sentence in the OP.

In node 0.6+, this will behave identically. Absolutely nothing needs to be documented that affect an older version of node than that :-)

**Review by nicolas377 — APPROVED** [review]
@isaacs LGTM! All the functionality this changes is out of scope of this package's supported node versions.

**Comment by isaacs** [comment]
> (We'll all be much happier if you choose not to ask why i need this change :-) )

Oh god, I think I know what's going on here lol 😂 

Do you need this backported to v7?  v8 is node 12+ already anyway.

**Comment by ljharb** [comment]
@isaacs ideally yes, but i understand if you're unwilling. either way this drastically reduces the number of n_m patches i need to float :-)

**Comment by isaacs** [comment]
Published on 7.2.2 and 8.0.3

**Pull request closed without merging**
