### PR TITLE
update(minimatch): bump minimatch version to >=3.0.2

### LINKED ISSUE #268: Bump minimatch version to >=3.0.2
According to NSP https://nodesecurity.io/advisories/118, minimatch is vulnerable to a regex DoS attack. Better to explicitly bump it to >= 3.0.2.

### PR DESCRIPTION
**Pull request by TDA**
Fixes #268 
@isaacs

### CODE REVIEW

**Comment by thomblake** [comment]
Those Travis failures sure are confusing

**Comment by TDA** [comment]
@thomblake I agree, no idea where requests@2.69.1 came in from :(

**Comment by thomblake** [comment]
@isaacs Any help on this one? Everyone is confused.

**Comment by isaacs** [comment]
The CI failures are because one of tap's deps added a dependency on a version of request that doesn't exist.

It's fixed, and also, I already bumped the minimatch version to `^3.0.2` before seeing this, so it's fine now.

Thanks.

**Pull request closed without merging**
