### PR TITLE
[Fix #290] allow magic charactors in top level directory on Windows

### LINKED ISSUE #290: C:\\* returns empty list
hi,
if you pass `C:\\*` or `C:/*` its returning nothing. Is there are trick to get the folder/file list on a root disc ? 
thanks,
g

### PR DESCRIPTION
**Pull request by loveky**

### CODE REVIEW

**Comment by loveky** [comment]
also related to https://github.com/webpack-contrib/copy-webpack-plugin/issues/266

**Comment by Amakaev** [comment]
i think u need to exclude package-lock.json from commit

**Comment by loveky** [comment]
@evilebottnawi I have updated the PR and the conflicts have been resolved. But the CI
 is failing due to Node version configured in CI service.

**Comment by evilebottnawi** [comment]
:disappointed:

**Comment by joerattz** [comment]
/cc @isaacs
/cc @loveky Can you explain how copy-webpack-plugin is dependent on isaacs/node-glob?  I don't see it.

Any progress on this?  Would really like to get Angular assets getting copied to dist folder when running in C:\Program Files (x86) due to Jenkins.  Seems like this should be a bigger problem.  Would like to see this fixed for a copy-webpack-plugin 4.6.X release.

**Comment by loveky** [comment]
@joerattz  copy-webpack-plugin depends on [globby](https://www.npmjs.com/package/globby) which depends on node-glob

**Comment by joerattz** [comment]
> @joerattz copy-webpack-plugin depends on [globby](https://www.npmjs.com/package/globby) which depends on node-glob

So is this fixed?  What do I need to do to get this working?

**Comment by loveky** [comment]
Nope, this is PR is still not merged. You have to change your build directory to walk around this issue.

**Comment by joerattz** [comment]
> Nope, this is PR is still not merged. You have to change your build directory to walk around this issue.

Can you explain how I would do that?  I don't understand what I need to do.  Any help would be appreciated.

**Comment by joerattz** [comment]
> Nope, this is PR is still not merged. You have to change your build directory to walk around this issue.

Do you mean by manually copying my assets to the dist dir?

**Comment by the-avid-engineer** [comment]
@joerattz GitHub Dependency Graph:

image

**Comment by isaacs** [comment]
Fixed at the root in v9.

**Pull request closed without merging**
