### PR TITLE
Add support for UNC paths

### LINKED ISSUE #74: Issue with UNC paths on Windows
When a UNC path is provided as part of the pattern to match, it is incorrectly transformed to an invalid path on the local computer.

e.x. `\\nas\node\` incorrectly becomes `/nas/node` which is treated as `C:\nas\node\`.

### PR DESCRIPTION
**Pull request by staticshock**
Wildcards that now work: \host\directory*

Wildcards that still don't work: \host*

Fixes #74 and #123

### CODE REVIEW

**Comment by isaacs** [comment]
Needs a test that fails without this patch, and passes with this patch.

**Comment by staticshock** [comment]
Yep, here you go. I'm not really good at node.js stuff, so let me know if this is on the right track. I have no idea if it's possible to create network shares without launching a subprocess, for instance. Also, no idea if global-leakage.js is going haywire here. Right now I'm seeing this on OS X, and I don't know what it means:

```
assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: "ArrayBuffer:Buffer:DTRACE_HTTP_CLIENT_REQUEST:DTRACE_HTTP_CLIENT_RESPONSE:DTRACE_HTTP_SERVER_REQUEST:DTRACE_HTTP_SERVER_RESPONS == "ArrayBuffer:Buffer:DTRACE_HTTP_CLIENT_REQUEST:DTRACE_HTTP_CLIENT_RESPONSE:DTRACE_HTTP_SERVER_REQUEST:DTRACE_HTTP_SERVER_RESPONS
    at process.<anonymous> (/Users/abacker/Dropbox/Projects/node-glob/test/global-leakage.js:10:10)
    at process.emit (events.js:95:17)
not ok test/unc-paths.js ................................ 0/1
    Command: "/usr/local/Cellar/node/0.10.36/bin/node unc-paths.js"
    TAP version 13
    not ok 1 test/unc-paths.js
      ---
        exit:    8
        stderr:  |
          assert.js:93
            throw new assert.AssertionError({
                  ^
          AssertionError: "ArrayBuffer:Buffer:DTRACE_HTTP_CLIENT_REQUEST:DTRACE_HTTP_CLIENT_RESPONSE:DTRACE_HTTP_SERVER_REQUEST:DTRACE_HTTP_SERVER_RESPONS == "ArrayBuffer:Buffer:DTRACE_HTTP_CLIENT_REQUEST:DTRACE_HTTP_CLIENT_RESPONSE:DTRACE_HTTP_SERVER_REQUEST:DTRACE_HTTP_SERVER_RESPONS
              at process.<anonymous> (/Users/abacker/Dropbox/Projects/node-glob/test/global-leakage.js:10:10)
              at process.emit (events.js:95:17)
        command: "/usr/local/Cellar/node/0.10.36/bin/node unc-paths.js"
      ...

    1..1
    # tests 1
    # fail  1
```

**Comment by staticshock** [comment]
Ah, I guess global-leakage.js was testing for the presence 'TAP_Global_Harness'. Fixed in the new version.

**Comment by isaacs** [comment]
Awesome, thanks.

My concern is that it's only running the test on Windows, and since most of the development (and ci) is running on unix, this won't catch it if I later break this functionality.  But now, since the tests pass on your windows system, at least I believe that it works ;)

A better approach might be to mock out the parts of the system so that the functionality can be tested on a Unix system as well.  The general pattern would be something like:

```javascript
// pretend to be windows
process.platform = 'win32'
// load glob before we muck around with fs's guts
var glob = require('../')
// mock out whatever we need to
var originalStat = fs.stat
fs.stat = function (path, cb) {
  // do whatever we want, based on the path
}
var originalReaddir = fs.readdir
fs.readdir = function (path, cb) {
  // whatever
}

test('wildcards in unc path', function (t) {
  glob('\\\\whatever\\*', function (er, results) {
    // make sure this is what we expect
    t.end()
  })
})
```

**Comment by heikki** [comment]
@isaacs There's [appveyor](http://www.appveyor.com/) if you want to run tests on windows too.

- http://www.appveyor.com/docs/lang/nodejs-iojs
- https://github.com/paulmillr/chokidar/blob/master/appveyor.yml

**Comment by staticshock** [comment]
I worry that I might mock something inexactly, and the tests would pass on unix and somehow still fail on Windows anyway. For instance, how should I simulate a case-insensitive stat call on a potentially case sensitive file system?

**Comment by staticshock** [comment]
@isaacs, I explored your suggestion briefly, and I don't think mocking the `fs` calls plays nicely with the current implementation. Specifically, I ran into a problem mocking `path.resolve`, and haven't figured out a solution yet. I have a separate ["work in progress" branch](https://github.com/staticshock/node-glob/commits/unc-path-tests) that demonstrates the attempt, and it doesn't really work on Windows or Linux.

**Comment by isaacs** [comment]
No longer an issue in v9.

**Pull request closed without merging**
