### PR TITLE
removing unused modules / variables and circular references

### PR DESCRIPTION
**Pull request by adrielcodeco**
the code "var Glob = require ('./ glob.js'). Glob" in sync.js is a circular reference
and others are not used

### CODE REVIEW

**Comment by adrielcodeco** [comment]
anybody can help here?

my changes do not impact to cause this error 
travis build successfully, but appveyor failed with this error: 

npm install
C:\Users\appveyor\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:82
      let notifier = require('update-notifier')({pkg})
      ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3

**Review by jimmywarting — APPROVED** [review]
LGTM

**Comment by kuraga** [comment]
Let's merge?

**Comment by kuraga** [comment]
@isaacs , @jimmywarting ,
merge, please! It resolves #365 ...

**Comment by jimmywarting** [comment]
I can't

**Comment by kuraga** [comment]
@isaacs , let's merge?

**Comment by kuraga** [comment]
@isaacs , ping

**Comment by kuraga** [comment]
@isaacs , why this couldn't be merged?

**Comment by kuraga** [comment]
@isaacs , merge, please!

**Comment by Trott** [comment]
If it helps anyone else, I resolved this in my own project by updating to the latest `@rollup/plugin-commonjs` and adding this to my config file:

```js
    commonjs({ dynamicRequireTargets: 'node_modules/glob/*.js' }),
```

**Comment by xup6m6fu04** [comment]
@isaacs , please merge

**Comment by jamesej** [comment]
A request for someone to fix and merge this as I actually get a runtime error in a setup with Rollup and Typescript which is caused by the circular dependency this resolves.

**Comment by kuraga** [comment]
@isaacs , please.

**Comment by isaacs** [comment]
No longer an issue in v9.

**Pull request closed without merging**
