### PR TITLE
Allow custom fs adapter to be passed as option (#280)

### PR DESCRIPTION
**Pull request by erikkemperman**
Maybe I should have allowed more time for negative feedback, but eager to get on with my planned refactor in `vinyl-fs` I figured I might as well take a stab at proposing something concrete.

### CODE REVIEW

**Comment by erikkemperman** [comment]
Maybe point out the obvious: I haven't considered changes for the sync case yet. Also, it just occurred to me I've just assumed custom adapters would support `cache` argument to `realpath` but probably shouldn't.

**Comment by erikkemperman** [comment]
I've added the synchronous counterpart, and tentatively simplified to pre-empt `realpath` calls entirely when a custom `fs` option is provided. Underestimated the implications of Node 6 slightly there.

Will leave this as it is for now, until you get a chance to look at this (or decide it's a bad idea), apologies for having submitted this a bit prematurely!

**Comment by erikkemperman** [comment]
Rebased onto latest master.

**Comment by erikkemperman** [comment]
Rebased again. Noticed failing test on Appveyor, have submitted a separate [PR](https://github.com/isaacs/node-glob/pull/303) which I believe addresses that.

@isaacs I appreciate you must be quite busy, but if possible I would be grateful for any quick feedback you might have here -- even if it's just that you don't like this idea... Thanks!

**Comment by isaacs** [comment]
This will have to be added as an option to https://github.com/isaacs/path-scurry.  If so, it'll be trivial to pass it along from glob.

**Pull request closed without merging**
